version: '3.9'
services:
  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"

  trivy-scan:
    image: aquasec/trivy
    command: ["image", "bkimminich/juice-shop"]
    depends_on:
      - juice-shop
    # chạy 1 lần rồi tự dừng
    restart: "no"

  zap:
    image: zaproxy/zap-stable
    user: zap
    command: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8080"]
    ports:
      - "8082:8080"

volumes:
  jenkins_home:

